apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/araszka-tenant/devfile-sample-go-basic/devfile-sample-go-basic@sha256:0dd61c40c75cfd64a290a1c8106f8f22124f28ae95cbbe14797afb4670bec809
        name: my-go
        resources: {}
status: {}
